### ISSUE TITLE
Error in parametric plot

### ISSUE THREAD

**Issue by jondo** [eagleoflqj/sympy_beta#2]
## Input
`plot(x=cos(t), y=sin(t))`
## How can it be better?
It should yield a plot instead of:
```
plot([ p1 = (cos(t), sin(t))
])
There was an error in Gamma. For reference the last five traceback entries are: Traceback (most recent call last):
  File "<exec>", line 15, in evcd
  File "/lib/python3.9/site-packages/gamma/logic.py", line 233, in eval_card
    result = card.eval(components, parameters)
  File "/lib/python3.9/site-packages/gamma/resultsets.py", line 95, in eval
    return self.card_info['eval_method'](components, parameters)
  File "/lib/python3.9/site-packages/gamma/resultsets.py", line 539, in eval_plot
    series = list(series.get_segments())
  File "/lib/python3.9/site-packages/sympy/plotting/plot.py", line 612, in get_segments
    points = type(self).get_data(self)
  File "/lib/python3.9/site-packages/sympy/plotting/plot.py", line 591, in get_data
    points = self.get_points()
  File "/lib/python3.9/site-packages/sympy/plotting/plot.py", line 923, in get_points
    sample(self.start, self.end, start, end, 0)
  File "/lib/python3.9/site-packages/sympy/plotting/plot.py", line 869, in sample
    random = 0.45 + np.random.rand() * 0.1
AttributeError: 'NoneType' object has no attribute 'random'
```

**Comment by eagleoflqj** [comment]
For some reason (maybe network) numpy isn't loaded in your case. Could you refresh to see if it goes normal (and optionally use F12 to check Network 4XX or 5XX)? I can reproduce it when I change `numpy` to a wrong name here:
https://github.com/eagleoflqj/sympy_beta/blob/c47b83ac283a43c8117d177c1d0155e0ed1e96c8/public/worker.js#L13
Anyway I should provide a notification to show something is wrong.

**Comment by jondo** [comment]
It repeatedly fails with [Fennec F-Droid](https://f-droid.org/de/packages/org.mozilla.fennec_fdroid/) 96.3.0 on my LineageOS 17.1 phone - both with mobile data and with WLAN, but it works with that phone's default web browser (Chromium 89).

For my tests, I have deactivated my Fennec add-ons.

It also works on another phone (Android 12) with the same Fennec F-Droid version in the same WLAN.
So the problem might not be easily reproducable - which can also be seen as good, i guess.

**Comment by eagleoflqj** [comment]
I tried Fennec F-Droid 96.3.0 on my HarmonyOS 2.0.0 (Android 10) and couldn't reproduce it either. I'll leave this issue open until a newer version of LineageOS and Fennec combination is confirmed to work.
